# Welcome to Jekyll!

# Website settings
title: "SpandaWorks"
description: "SpandaWorks: Life, Consciousness, Energy, Tantra, Yoga, Dance, Travel, Life."
keywords: "Life,Consciousness,Energy,Tantra,Yoga,Dance,Travel,Life."
baseurl: "/"
url: "http://spandaworks.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'SpandaWorks'
  email: 'zelenko@gmail.com'
  facebook_username: 'dzelenko'
#  github_username: 'spandaworks'
  head_img: 'static/img/landing/face.jpg'
  desc: ''

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'blog'
    i18n: 'nav.blog'
    link: 'nav.blog-link'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

   # - id: 'links'
   #  i18n: 'nav.link'
   #  name: 'Links'
   #  tpl: 'links.html'
   #  css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
    text: 'ENG'
  - locale: 'ru'
    flag: 'static/img/flags/Russia.png'
    text: 'РУС'

# blog img path
img_path: 'http://spandaworks.github.io/static/img/blog'
# img_path: 'http://localhost:4000/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
